import { IMAGES } from '../content/images.js';

// Renders a venue screenshot with its intrinsic width/height (so the browser
// reserves space before decode and the layout does not shift) and a srcset
// generated by scripts/generate-images.mjs (so a phone does not download a
// 2000px screenshot for a 274px slot).
//
// `sizes` should describe the slot the image occupies at each breakpoint. It
// defaults to full-viewport-width, which is safe but pessimistic - pass a real
// value wherever the rendered width is known.
export default function Shot({
  src,
  alt,
  sizes = '100vw',
  priority = false,
  className,
  ...rest
}) {
  const meta = IMAGES[src];

  return (
    <img
      src={src}
      alt={alt}
      className={className}
      width={meta?.width}
      height={meta?.height}
      srcSet={meta?.srcset}
      sizes={meta ? sizes : undefined}
      loading={priority ? 'eager' : 'lazy'}
      fetchpriority={priority ? 'high' : 'auto'}
      decoding="async"
      {...rest}
    />
  );
}
