// GENERATED by scripts/generate-images.mjs - do not edit by hand.
// Run `npm run images` to regenerate after changing anything in public/live.
export const IMAGES = {
  "/live/admin-analytics.webp": {
    "width": 2000,
    "height": 1069,
    "srcset": "/live/admin-analytics-480w.webp 480w, /live/admin-analytics-720w.webp 720w, /live/admin-analytics-960w.webp 960w, /live/admin-analytics-1440w.webp 1440w, /live/admin-analytics.webp 2000w"
  },
  "/live/admin-menu.webp": {
    "width": 2000,
    "height": 1051,
    "srcset": "/live/admin-menu-480w.webp 480w, /live/admin-menu-720w.webp 720w, /live/admin-menu-960w.webp 960w, /live/admin-menu-1440w.webp 1440w, /live/admin-menu.webp 2000w"
  },
  "/live/admin-payroll.webp": {
    "width": 2000,
    "height": 1037,
    "srcset": "/live/admin-payroll-480w.webp 480w, /live/admin-payroll-720w.webp 720w, /live/admin-payroll-960w.webp 960w, /live/admin-payroll-1440w.webp 1440w, /live/admin-payroll.webp 2000w"
  },
  "/live/beach-road-wip-1.webp": {
    "width": 1600,
    "height": 830,
    "srcset": "/live/beach-road-wip-1-480w.webp 480w, /live/beach-road-wip-1-720w.webp 720w, /live/beach-road-wip-1-960w.webp 960w, /live/beach-road-wip-1-1440w.webp 1440w, /live/beach-road-wip-1.webp 1600w"
  },
  "/live/beach-road-wip-2.webp": {
    "width": 1600,
    "height": 829,
    "srcset": "/live/beach-road-wip-2-480w.webp 480w, /live/beach-road-wip-2-720w.webp 720w, /live/beach-road-wip-2-960w.webp 960w, /live/beach-road-wip-2-1440w.webp 1440w, /live/beach-road-wip-2.webp 1600w"
  },
  "/live/beach-road-wip-3.webp": {
    "width": 1600,
    "height": 825,
    "srcset": "/live/beach-road-wip-3-480w.webp 480w, /live/beach-road-wip-3-720w.webp 720w, /live/beach-road-wip-3-960w.webp 960w, /live/beach-road-wip-3-1440w.webp 1440w, /live/beach-road-wip-3.webp 1600w"
  },
  "/live/needa-pizza-wip.webp": {
    "width": 1600,
    "height": 806,
    "srcset": "/live/needa-pizza-wip-480w.webp 480w, /live/needa-pizza-wip-720w.webp 720w, /live/needa-pizza-wip-960w.webp 960w, /live/needa-pizza-wip-1440w.webp 1440w, /live/needa-pizza-wip.webp 1600w"
  },
  "/live/ordering-mobile.webp": {
    "width": 900,
    "height": 1692,
    "srcset": "/live/ordering-mobile-480w.webp 480w, /live/ordering-mobile-720w.webp 720w, /live/ordering-mobile.webp 900w"
  },
  "/live/staff-availability.webp": {
    "width": 2000,
    "height": 1007,
    "srcset": "/live/staff-availability-480w.webp 480w, /live/staff-availability-720w.webp 720w, /live/staff-availability-960w.webp 960w, /live/staff-availability-1440w.webp 1440w, /live/staff-availability.webp 2000w"
  },
  "/live/staff-orders.webp": {
    "width": 2000,
    "height": 1008,
    "srcset": "/live/staff-orders-480w.webp 480w, /live/staff-orders-720w.webp 720w, /live/staff-orders-960w.webp 960w, /live/staff-orders-1440w.webp 1440w, /live/staff-orders.webp 2000w"
  },
  "/live/staff-time-clock.webp": {
    "width": 2000,
    "height": 1013,
    "srcset": "/live/staff-time-clock-480w.webp 480w, /live/staff-time-clock-720w.webp 720w, /live/staff-time-clock-960w.webp 960w, /live/staff-time-clock-1440w.webp 1440w, /live/staff-time-clock.webp 2000w"
  },
  "/live/venue-home.webp": {
    "width": 2000,
    "height": 1013,
    "srcset": "/live/venue-home-480w.webp 480w, /live/venue-home-720w.webp 720w, /live/venue-home-960w.webp 960w, /live/venue-home-1440w.webp 1440w, /live/venue-home.webp 2000w"
  }
};
