// Generates responsive variants for the venue screenshots and writes a manifest
// of intrinsic dimensions + srcset strings to src/content/images.js.
//
// Two problems this solves:
//   1. No <img> on the site carried width/height, so every image shifted the
//      layout as it decoded - including two eager hero images.
//   2. Full 2000px screenshots were served into 258-343px mobile slots, up to
//      3.9x more pixel data than a DPR-2 phone can display.
//
// Run with `npm run images` after adding or replacing anything in public/live.
// Generated variants are committed so the production build stays dependency-free.
import { readdir, writeFile } from 'node:fs/promises';
import { join, parse } from 'node:path';
import sharp from 'sharp';

const SOURCE_DIR = 'public/live';
// 720 matters: the portrait ordering screenshot renders ~274px wide, which needs
// ~550px at DPR 2. Without a rung there it jumps straight to the 900px original.
const WIDTHS = [480, 720, 960, 1440];
const VARIANT_PATTERN = /-\d+w$/;

const files = (await readdir(SOURCE_DIR))
  .filter((name) => name.endsWith('.webp'))
  .filter((name) => !VARIANT_PATTERN.test(parse(name).name));

const manifest = {};

for (const file of files) {
  const { name } = parse(file);
  const sourcePath = join(SOURCE_DIR, file);
  const image = sharp(sourcePath);
  const { width, height } = await image.metadata();

  const sources = [];

  for (const target of WIDTHS) {
    // Never upscale - a variant wider than the original is pure waste.
    if (target >= width) continue;
    const variantName = `${name}-${target}w.webp`;
    await sharp(sourcePath)
      .resize({ width: target, withoutEnlargement: true })
      .webp({ quality: 78, effort: 5 })
      .toFile(join(SOURCE_DIR, variantName));
    sources.push({ url: `/live/${variantName}`, width: target });
  }

  sources.push({ url: `/live/${file}`, width });

  manifest[`/live/${file}`] = {
    width,
    height,
    srcset: sources.map((s) => `${s.url} ${s.width}w`).join(', '),
  };

  console.log(`${file}  ${width}x${height}  -> ${sources.length} sources`);
}

const body = `// GENERATED by scripts/generate-images.mjs - do not edit by hand.
// Run \`npm run images\` to regenerate after changing anything in public/live.
export const IMAGES = ${JSON.stringify(manifest, null, 2)};
`;

await writeFile('src/content/images.js', body, 'utf8');
console.log(`\nWrote src/content/images.js (${Object.keys(manifest).length} images)`);
